/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sql_parser_Transakcije */

#ifndef _Included_sql_parser_Transakcije
#define _Included_sql_parser_Transakcije
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sql_parser_Transakcije
 * Method:    azuriraj
 * Signature: (I)V
 */
	JNIEXPORT void JNICALL Java_sql_1parser_Transakcije_azuriraj
	(JNIEnv*, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
