/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sql_parser_Akcije */

#ifndef _Included_sql_parser_Akcije
#define _Included_sql_parser_Akcije
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sql_parser_Akcije
 * Method:    azuriraj
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sql_1parser_Akcije_azuriraj
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
