/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sql_parser_SQLParser */

#ifndef _Included_sql_parser_SQLParser
#define _Included_sql_parser_SQLParser
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     sql_parser_SQLParser
	 * Method:    kupi
	 * Signature: (ILjava/lang/String;ID)I
	 */
	JNIEXPORT jint JNICALL Java_sql_1parser_SQLParser_kupi
	(JNIEnv*, jobject, jint, jstring, jint, jdouble);

	/*
	 * Class:     sql_parser_SQLParser
	 * Method:    prodaj
	 * Signature: (IIDI)I
	 */
	JNIEXPORT jint JNICALL Java_sql_1parser_SQLParser_prodaj
	(JNIEnv*, jobject, jint, jint, jdouble, jint);

	/*
	 * Class:     sql_parser_SQLParser
	 * Method:    simbol
	 * Signature: (I)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_sql_1parser_SQLParser_simbol
	(JNIEnv*, jobject, jint);

	/*
	 * Class:     sql_parser_SQLParser
	 * Method:    loginPass
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_sql_1parser_SQLParser_loginPass
	(JNIEnv*, jclass, jstring, jstring);

	/*
	 * Class:     sql_parser_SQLParser
	 * Method:    registracije
	 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_sql_1parser_SQLParser_registracije
	(JNIEnv*, jclass, jstring, jstring, jint);

	/*
	 * Class:     sql_parser_SQLParser
	 * Method:    novac
	 * Signature: (I)D
	 */
	JNIEXPORT jdouble JNICALL Java_sql_1parser_SQLParser_novac
	(JNIEnv*, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
