/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class parser_Podaci */

#ifndef _Included_parser_Podaci
#define _Included_parser_Podaci
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     parser_Podaci
	 * Method:    parse
	 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
	 */
	JNIEXPORT void JNICALL Java_parser_Podaci_parse
	(JNIEnv*, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
